import { parsePlaylist } from './lib/playlist-parser.js';
import { calculateEta, formatEta } from './lib/eta.js';
import { DEFAULT_PROMPT, formatFilename, inferExtension } from './lib/filename.js';

const $ = selector => document.querySelector(selector);
let sources = [], selected = null, tab, lastEta = null;
const els = { title: $('#page-title'), origin: $('#page-origin'), count: $('#count'), list: $('#sources'), status: $('#status'), prompt: $('#prompt'), preview: $('#preview'), note: $('#preview-note'), meta: $('#preview-meta'), history: $('#history') };

init();
async function init() {
  [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
  await chrome.scripting.executeScript({ target: { tabId: tab.id }, files: ['content.js'] }).catch(() => {});
  const stored = await chrome.storage.local.get(['prompt', 'quickDownload', 'history']);
  els.prompt.value = stored.prompt || DEFAULT_PROMPT; $('#quick-download').checked = Boolean(stored.quickDownload); renderHistory(stored.history || []);
  chrome.runtime.onMessage.addListener(message => { if (message.type === 'DOWNLOAD_PROGRESS') updateProgress(message); });
  const restoredDownloads = await chrome.runtime.sendMessage({ type: 'GET_DOWNLOAD_STATES' }).catch(() => []);
  restoredDownloads.filter(item => ['starting', 'downloading', 'assembling', 'resuming', 'retrying', 'interrupted'].includes(item.status)).forEach(updateProgress);
  $('#rescan').onclick = () => chrome.tabs.sendMessage(tab.id, { type: 'RESCAN' });
  $('#options').onclick = () => chrome.runtime.openOptionsPage();
  $('#quick-download').onchange = event => chrome.storage.local.set({ quickDownload: event.target.checked });
  $('#quick-action').onclick = () => selected && download(selected);
  $('#download-all').onclick = () => Promise.all(sources.filter(source => source.downloadable !== false && !source.isDRM).map(download));
  els.prompt.onchange = () => chrome.storage.local.set({ prompt: els.prompt.value });
  document.querySelectorAll('[data-fragment]').forEach(button => button.onclick = () => { const fragment = button.dataset.fragment; if (!els.prompt.value.toLowerCase().includes(fragment.toLowerCase())) els.prompt.value += `; ${fragment}`; els.prompt.dispatchEvent(new Event('change')); });
  const response = await requestSources();
  if (response) {
    const network = await chrome.runtime.sendMessage({ type: 'GET_NETWORK_SOURCES', tabId: tab.id }).catch(() => []);
    applySources({ ...response, sources: [...(response.sources || []), ...network.filter(item => !(response.sources || []).some(source => source.src === item.src))] });
  } else els.status.textContent = 'Cannot scan this page';
}
async function requestSources() {
  for (let attempt = 0; attempt < 3; attempt += 1) {
    const response = await chrome.tabs.sendMessage(tab.id, { type: 'GET_SOURCES' }).catch(() => null);
    if (response) return response;
    await new Promise(resolve => setTimeout(resolve, 150));
  }
  return null;
}
function applySources(response) { sources = response.sources || []; els.title.textContent = response.title || 'Current page'; els.origin.textContent = response.pageUrl ? new URL(response.pageUrl).host : ''; els.count.textContent = sources.length; renderSources(); if (sources[0]) selectSource(sources[0]); $('#quick-action').hidden = !storedQuickDownload(); }
function storedQuickDownload() { return $('#quick-download').checked; }
function renderSources() { els.list.replaceChildren(...sources.map((source, index) => { const card = document.createElement('article'); card.className = 'source-card'; card.dataset.index = index; const resolution = source.resolution?.height ? `${source.resolution.height}p` : 'Adaptive'; const type = (source.mime || source.src.match(/\.([a-z0-9]+)(?:[?#]|$)/i)?.[1] || 'stream').toUpperCase(); const poster = source.poster ? `<img class="source-thumb" src="${escapeHtml(source.poster)}" alt="">` : `<span class="source-thumb source-thumb-fallback">▶</span>`; const downloadLabel = source.downloadable === false ? 'Open' : 'Download'; card.innerHTML = `<div class="source-row">${poster}<div class="source-main"><div class="source-title" title="${escapeHtml(source.src)}">${escapeHtml(source.label || 'Video source')}</div><div class="muted source-host">${escapeHtml(source.originHost || '')}</div><div class="tags"><span class="tag">${resolution}</span><span class="tag">${type}</span><span class="tag ${source.isDRM ? 'tag-warning' : ''}">${source.isDRM ? 'Protected' : 'Ready'}</span></div></div><button class="primary download-action" aria-label="${downloadLabel} ${escapeHtml(source.label || 'video')}">${downloadLabel}</button></div><div class="card-actions"><button class="secondary preview-action">Preview</button><button class="secondary copy-action">Copy URL</button><button class="secondary open-action">Open ↗</button></div><details><summary>Details</summary><div class="details">URL: ${escapeHtml(source.src)}<br>Codec: ${escapeHtml(source.codecs || 'Unknown')}<br>Estimated size: ${escapeHtml(source.estimatedSize || 'Unknown')}<br>Subtitles: ${source.subtitles?.length ? 'Available' : 'None detected'}</div></details>`; card.querySelector('.preview-action').onclick = () => selectSource(source); card.querySelector('.download-action').onclick = () => source.downloadable === false ? chrome.tabs.create({ url: source.src }) : download(source); card.querySelector('.copy-action').onclick = () => navigator.clipboard.writeText(source.src); card.querySelector('.open-action').onclick = () => chrome.tabs.create({ url: source.src }); return card; })); }
async function selectSource(source) { selected = source; document.querySelectorAll('.source-card').forEach(card => card.classList.toggle('selected', sources[Number(card.dataset.index)] === source)); els.preview.removeAttribute('src'); els.note.textContent = 'Preparing preview…'; els.meta.textContent = `${source.originHost || ''} · ${source.resolution?.height ? `${source.resolution.height}p` : 'Adaptive'}`; if (/\.m3u8(?:[?#]|$)/i.test(source.src)) { try { const response = await fetch(source.src, { credentials: 'include' }); const text = await response.text(); const variants = parsePlaylist(text, source.src); source.type = 'hls'; source.variants = variants; if (variants.length) { sources = [source, ...variants.filter(variant => !sources.some(item => item.src === variant.src))]; renderSources(); els.note.textContent = `HLS master: ${variants.length} quality variants found. Native playback is used when supported.`; } else els.note.textContent = 'HLS playlist found. This browser may need native HLS support.'; els.preview.src = source.src; els.preview.play().catch(() => {}); } catch { els.note.textContent = 'Playlist blocked by CORS. Open the playlist or use a permitted server proxy.'; } } else { els.preview.src = source.src; els.note.textContent = 'Direct preview'; els.preview.play().catch(() => {}); } }
async function download(source) { const quality = source.resolution?.height ? `${source.resolution.height}p` : 'adaptive'; const ext = inferExtension(source); const filename = formatFilename(els.prompt.value, { title: source.title || els.title.textContent, quality, bitrate: source.bitrate || '', origin: source.originHost || '', ext }); const result = await chrome.runtime.sendMessage({ type: 'START_DOWNLOAD', source, filename, title: els.title.textContent }); if (result?.ok) { els.status.textContent = 'Download started'; saveHistory({ filename, source }); } else { els.status.textContent = result?.error || 'Download unavailable'; if (result?.playlist) chrome.tabs.create({ url: result.playlist }); } }
function saveHistory(item) { chrome.storage.local.get('history').then(({ history = [] }) => chrome.storage.local.set({ history: [item, ...history].slice(0, 8) })); }
function renderHistory(history) { if (!history.length) return; els.history.replaceChildren(...history.map(item => { const row = document.createElement('div'); row.className = 'history-item'; row.innerHTML = `<span>${escapeHtml(item.filename)}</span><button class="secondary">↻</button>`; row.querySelector('button').onclick = () => download(item.source); return row; })); }
function updateProgress(message) { if (message.status === 'complete') { els.status.textContent = 'Download complete'; return; } if (['error', 'interrupted', 'playlist-fallback'].includes(message.status)) els.status.textContent = message.error || 'Download paused'; const percent = message.total ? Math.round(message.received / message.total * 100) : 0; let bar = $('#active-progress'); if (!bar) { bar = document.createElement('div'); bar.id = 'active-progress'; bar.innerHTML = '<span class="droplet"></span><div class="progress"><div class="fill"></div></div><small class="muted">0% · --:--</small>'; els.status.after(bar); } const elapsed = Date.now() - (message.startedAt || Date.now()); lastEta = calculateEta(message.received, message.total, elapsed, lastEta); bar.querySelector('.fill').style.width = `${percent}%`; bar.querySelector('small').textContent = `${message.status === 'retrying' || message.status === 'resuming' ? `${message.status} · ` : ''}${percent}% · ${formatEta(lastEta)}`; }
function escapeHtml(value) { return String(value ?? '').replace(/[&<>"']/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[character])); }